
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Accident` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Accident
 * 
 */
export type AccidentModel = runtime.Types.Result.DefaultSelection<Prisma.$AccidentPayload>

export type AggregateAccident = {
  _count: AccidentCountAggregateOutputType | null
  _avg: AccidentAvgAggregateOutputType | null
  _sum: AccidentSumAggregateOutputType | null
  _min: AccidentMinAggregateOutputType | null
  _max: AccidentMaxAggregateOutputType | null
}

export type AccidentAvgAggregateOutputType = {
  locationLat: runtime.Decimal | null
  locationLng: runtime.Decimal | null
}

export type AccidentSumAggregateOutputType = {
  locationLat: runtime.Decimal | null
  locationLng: runtime.Decimal | null
}

export type AccidentMinAggregateOutputType = {
  id: string | null
  tenantId: string | null
  userId: string | null
  fullName: string | null
  lastName: string | null
  locationLat: runtime.Decimal | null
  locationLng: runtime.Decimal | null
  addressText: string | null
  accidentType: string | null
  createdAt: Date | null
}

export type AccidentMaxAggregateOutputType = {
  id: string | null
  tenantId: string | null
  userId: string | null
  fullName: string | null
  lastName: string | null
  locationLat: runtime.Decimal | null
  locationLng: runtime.Decimal | null
  addressText: string | null
  accidentType: string | null
  createdAt: Date | null
}

export type AccidentCountAggregateOutputType = {
  id: number
  tenantId: number
  userId: number
  fullName: number
  lastName: number
  locationLat: number
  locationLng: number
  addressText: number
  accidentType: number
  sceneData: number
  createdAt: number
  _all: number
}


export type AccidentAvgAggregateInputType = {
  locationLat?: true
  locationLng?: true
}

export type AccidentSumAggregateInputType = {
  locationLat?: true
  locationLng?: true
}

export type AccidentMinAggregateInputType = {
  id?: true
  tenantId?: true
  userId?: true
  fullName?: true
  lastName?: true
  locationLat?: true
  locationLng?: true
  addressText?: true
  accidentType?: true
  createdAt?: true
}

export type AccidentMaxAggregateInputType = {
  id?: true
  tenantId?: true
  userId?: true
  fullName?: true
  lastName?: true
  locationLat?: true
  locationLng?: true
  addressText?: true
  accidentType?: true
  createdAt?: true
}

export type AccidentCountAggregateInputType = {
  id?: true
  tenantId?: true
  userId?: true
  fullName?: true
  lastName?: true
  locationLat?: true
  locationLng?: true
  addressText?: true
  accidentType?: true
  sceneData?: true
  createdAt?: true
  _all?: true
}

export type AccidentAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Accident to aggregate.
   */
  where?: Prisma.AccidentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Accidents to fetch.
   */
  orderBy?: Prisma.AccidentOrderByWithRelationInput | Prisma.AccidentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AccidentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Accidents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Accidents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Accidents
  **/
  _count?: true | AccidentCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AccidentAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AccidentSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AccidentMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AccidentMaxAggregateInputType
}

export type GetAccidentAggregateType<T extends AccidentAggregateArgs> = {
      [P in keyof T & keyof AggregateAccident]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAccident[P]>
    : Prisma.GetScalarType<T[P], AggregateAccident[P]>
}




export type AccidentGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AccidentWhereInput
  orderBy?: Prisma.AccidentOrderByWithAggregationInput | Prisma.AccidentOrderByWithAggregationInput[]
  by: Prisma.AccidentScalarFieldEnum[] | Prisma.AccidentScalarFieldEnum
  having?: Prisma.AccidentScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AccidentCountAggregateInputType | true
  _avg?: AccidentAvgAggregateInputType
  _sum?: AccidentSumAggregateInputType
  _min?: AccidentMinAggregateInputType
  _max?: AccidentMaxAggregateInputType
}

export type AccidentGroupByOutputType = {
  id: string
  tenantId: string
  userId: string
  fullName: string
  lastName: string
  locationLat: runtime.Decimal
  locationLng: runtime.Decimal
  addressText: string
  accidentType: string
  sceneData: runtime.JsonValue
  createdAt: Date
  _count: AccidentCountAggregateOutputType | null
  _avg: AccidentAvgAggregateOutputType | null
  _sum: AccidentSumAggregateOutputType | null
  _min: AccidentMinAggregateOutputType | null
  _max: AccidentMaxAggregateOutputType | null
}

export type GetAccidentGroupByPayload<T extends AccidentGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AccidentGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AccidentGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AccidentGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AccidentGroupByOutputType[P]>
      }
    >
  >



export type AccidentWhereInput = {
  AND?: Prisma.AccidentWhereInput | Prisma.AccidentWhereInput[]
  OR?: Prisma.AccidentWhereInput[]
  NOT?: Prisma.AccidentWhereInput | Prisma.AccidentWhereInput[]
  id?: Prisma.StringFilter<"Accident"> | string
  tenantId?: Prisma.StringFilter<"Accident"> | string
  userId?: Prisma.StringFilter<"Accident"> | string
  fullName?: Prisma.StringFilter<"Accident"> | string
  lastName?: Prisma.StringFilter<"Accident"> | string
  locationLat?: Prisma.DecimalFilter<"Accident"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  locationLng?: Prisma.DecimalFilter<"Accident"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  addressText?: Prisma.StringFilter<"Accident"> | string
  accidentType?: Prisma.StringFilter<"Accident"> | string
  sceneData?: Prisma.JsonFilter<"Accident">
  createdAt?: Prisma.DateTimeFilter<"Accident"> | Date | string
  tenant?: Prisma.XOR<Prisma.TenantScalarRelationFilter, Prisma.TenantWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  photos?: Prisma.AccidentPhotoListRelationFilter
}

export type AccidentOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  tenantId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  lastName?: Prisma.SortOrder
  locationLat?: Prisma.SortOrder
  locationLng?: Prisma.SortOrder
  addressText?: Prisma.SortOrder
  accidentType?: Prisma.SortOrder
  sceneData?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  tenant?: Prisma.TenantOrderByWithRelationInput
  user?: Prisma.UserOrderByWithRelationInput
  photos?: Prisma.AccidentPhotoOrderByRelationAggregateInput
}

export type AccidentWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.AccidentWhereInput | Prisma.AccidentWhereInput[]
  OR?: Prisma.AccidentWhereInput[]
  NOT?: Prisma.AccidentWhereInput | Prisma.AccidentWhereInput[]
  tenantId?: Prisma.StringFilter<"Accident"> | string
  userId?: Prisma.StringFilter<"Accident"> | string
  fullName?: Prisma.StringFilter<"Accident"> | string
  lastName?: Prisma.StringFilter<"Accident"> | string
  locationLat?: Prisma.DecimalFilter<"Accident"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  locationLng?: Prisma.DecimalFilter<"Accident"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  addressText?: Prisma.StringFilter<"Accident"> | string
  accidentType?: Prisma.StringFilter<"Accident"> | string
  sceneData?: Prisma.JsonFilter<"Accident">
  createdAt?: Prisma.DateTimeFilter<"Accident"> | Date | string
  tenant?: Prisma.XOR<Prisma.TenantScalarRelationFilter, Prisma.TenantWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  photos?: Prisma.AccidentPhotoListRelationFilter
}, "id">

export type AccidentOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  tenantId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  lastName?: Prisma.SortOrder
  locationLat?: Prisma.SortOrder
  locationLng?: Prisma.SortOrder
  addressText?: Prisma.SortOrder
  accidentType?: Prisma.SortOrder
  sceneData?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.AccidentCountOrderByAggregateInput
  _avg?: Prisma.AccidentAvgOrderByAggregateInput
  _max?: Prisma.AccidentMaxOrderByAggregateInput
  _min?: Prisma.AccidentMinOrderByAggregateInput
  _sum?: Prisma.AccidentSumOrderByAggregateInput
}

export type AccidentScalarWhereWithAggregatesInput = {
  AND?: Prisma.AccidentScalarWhereWithAggregatesInput | Prisma.AccidentScalarWhereWithAggregatesInput[]
  OR?: Prisma.AccidentScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AccidentScalarWhereWithAggregatesInput | Prisma.AccidentScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Accident"> | string
  tenantId?: Prisma.StringWithAggregatesFilter<"Accident"> | string
  userId?: Prisma.StringWithAggregatesFilter<"Accident"> | string
  fullName?: Prisma.StringWithAggregatesFilter<"Accident"> | string
  lastName?: Prisma.StringWithAggregatesFilter<"Accident"> | string
  locationLat?: Prisma.DecimalWithAggregatesFilter<"Accident"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  locationLng?: Prisma.DecimalWithAggregatesFilter<"Accident"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  addressText?: Prisma.StringWithAggregatesFilter<"Accident"> | string
  accidentType?: Prisma.StringWithAggregatesFilter<"Accident"> | string
  sceneData?: Prisma.JsonWithAggregatesFilter<"Accident">
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Accident"> | Date | string
}

export type AccidentCreateInput = {
  id?: string
  fullName: string
  lastName: string
  locationLat: runtime.Decimal | runtime.DecimalJsLike | number | string
  locationLng: runtime.Decimal | runtime.DecimalJsLike | number | string
  addressText: string
  accidentType: string
  sceneData: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  tenant: Prisma.TenantCreateNestedOneWithoutAccidentsInput
  user: Prisma.UserCreateNestedOneWithoutAccidentsInput
  photos?: Prisma.AccidentPhotoCreateNestedManyWithoutAccidentInput
}

export type AccidentUncheckedCreateInput = {
  id?: string
  tenantId: string
  userId: string
  fullName: string
  lastName: string
  locationLat: runtime.Decimal | runtime.DecimalJsLike | number | string
  locationLng: runtime.Decimal | runtime.DecimalJsLike | number | string
  addressText: string
  accidentType: string
  sceneData: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  photos?: Prisma.AccidentPhotoUncheckedCreateNestedManyWithoutAccidentInput
}

export type AccidentUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  locationLat?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  locationLng?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  addressText?: Prisma.StringFieldUpdateOperationsInput | string
  accidentType?: Prisma.StringFieldUpdateOperationsInput | string
  sceneData?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tenant?: Prisma.TenantUpdateOneRequiredWithoutAccidentsNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutAccidentsNestedInput
  photos?: Prisma.AccidentPhotoUpdateManyWithoutAccidentNestedInput
}

export type AccidentUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  locationLat?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  locationLng?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  addressText?: Prisma.StringFieldUpdateOperationsInput | string
  accidentType?: Prisma.StringFieldUpdateOperationsInput | string
  sceneData?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  photos?: Prisma.AccidentPhotoUncheckedUpdateManyWithoutAccidentNestedInput
}

export type AccidentCreateManyInput = {
  id?: string
  tenantId: string
  userId: string
  fullName: string
  lastName: string
  locationLat: runtime.Decimal | runtime.DecimalJsLike | number | string
  locationLng: runtime.Decimal | runtime.DecimalJsLike | number | string
  addressText: string
  accidentType: string
  sceneData: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type AccidentUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  locationLat?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  locationLng?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  addressText?: Prisma.StringFieldUpdateOperationsInput | string
  accidentType?: Prisma.StringFieldUpdateOperationsInput | string
  sceneData?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AccidentUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  locationLat?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  locationLng?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  addressText?: Prisma.StringFieldUpdateOperationsInput | string
  accidentType?: Prisma.StringFieldUpdateOperationsInput | string
  sceneData?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AccidentListRelationFilter = {
  every?: Prisma.AccidentWhereInput
  some?: Prisma.AccidentWhereInput
  none?: Prisma.AccidentWhereInput
}

export type AccidentOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AccidentCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tenantId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  lastName?: Prisma.SortOrder
  locationLat?: Prisma.SortOrder
  locationLng?: Prisma.SortOrder
  addressText?: Prisma.SortOrder
  accidentType?: Prisma.SortOrder
  sceneData?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AccidentAvgOrderByAggregateInput = {
  locationLat?: Prisma.SortOrder
  locationLng?: Prisma.SortOrder
}

export type AccidentMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tenantId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  lastName?: Prisma.SortOrder
  locationLat?: Prisma.SortOrder
  locationLng?: Prisma.SortOrder
  addressText?: Prisma.SortOrder
  accidentType?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AccidentMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tenantId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  lastName?: Prisma.SortOrder
  locationLat?: Prisma.SortOrder
  locationLng?: Prisma.SortOrder
  addressText?: Prisma.SortOrder
  accidentType?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AccidentSumOrderByAggregateInput = {
  locationLat?: Prisma.SortOrder
  locationLng?: Prisma.SortOrder
}

export type AccidentScalarRelationFilter = {
  is?: Prisma.AccidentWhereInput
  isNot?: Prisma.AccidentWhereInput
}

export type AccidentCreateNestedManyWithoutTenantInput = {
  create?: Prisma.XOR<Prisma.AccidentCreateWithoutTenantInput, Prisma.AccidentUncheckedCreateWithoutTenantInput> | Prisma.AccidentCreateWithoutTenantInput[] | Prisma.AccidentUncheckedCreateWithoutTenantInput[]
  connectOrCreate?: Prisma.AccidentCreateOrConnectWithoutTenantInput | Prisma.AccidentCreateOrConnectWithoutTenantInput[]
  createMany?: Prisma.AccidentCreateManyTenantInputEnvelope
  connect?: Prisma.AccidentWhereUniqueInput | Prisma.AccidentWhereUniqueInput[]
}

export type AccidentUncheckedCreateNestedManyWithoutTenantInput = {
  create?: Prisma.XOR<Prisma.AccidentCreateWithoutTenantInput, Prisma.AccidentUncheckedCreateWithoutTenantInput> | Prisma.AccidentCreateWithoutTenantInput[] | Prisma.AccidentUncheckedCreateWithoutTenantInput[]
  connectOrCreate?: Prisma.AccidentCreateOrConnectWithoutTenantInput | Prisma.AccidentCreateOrConnectWithoutTenantInput[]
  createMany?: Prisma.AccidentCreateManyTenantInputEnvelope
  connect?: Prisma.AccidentWhereUniqueInput | Prisma.AccidentWhereUniqueInput[]
}

export type AccidentUpdateManyWithoutTenantNestedInput = {
  create?: Prisma.XOR<Prisma.AccidentCreateWithoutTenantInput, Prisma.AccidentUncheckedCreateWithoutTenantInput> | Prisma.AccidentCreateWithoutTenantInput[] | Prisma.AccidentUncheckedCreateWithoutTenantInput[]
  connectOrCreate?: Prisma.AccidentCreateOrConnectWithoutTenantInput | Prisma.AccidentCreateOrConnectWithoutTenantInput[]
  upsert?: Prisma.AccidentUpsertWithWhereUniqueWithoutTenantInput | Prisma.AccidentUpsertWithWhereUniqueWithoutTenantInput[]
  createMany?: Prisma.AccidentCreateManyTenantInputEnvelope
  set?: Prisma.AccidentWhereUniqueInput | Prisma.AccidentWhereUniqueInput[]
  disconnect?: Prisma.AccidentWhereUniqueInput | Prisma.AccidentWhereUniqueInput[]
  delete?: Prisma.AccidentWhereUniqueInput | Prisma.AccidentWhereUniqueInput[]
  connect?: Prisma.AccidentWhereUniqueInput | Prisma.AccidentWhereUniqueInput[]
  update?: Prisma.AccidentUpdateWithWhereUniqueWithoutTenantInput | Prisma.AccidentUpdateWithWhereUniqueWithoutTenantInput[]
  updateMany?: Prisma.AccidentUpdateManyWithWhereWithoutTenantInput | Prisma.AccidentUpdateManyWithWhereWithoutTenantInput[]
  deleteMany?: Prisma.AccidentScalarWhereInput | Prisma.AccidentScalarWhereInput[]
}

export type AccidentUncheckedUpdateManyWithoutTenantNestedInput = {
  create?: Prisma.XOR<Prisma.AccidentCreateWithoutTenantInput, Prisma.AccidentUncheckedCreateWithoutTenantInput> | Prisma.AccidentCreateWithoutTenantInput[] | Prisma.AccidentUncheckedCreateWithoutTenantInput[]
  connectOrCreate?: Prisma.AccidentCreateOrConnectWithoutTenantInput | Prisma.AccidentCreateOrConnectWithoutTenantInput[]
  upsert?: Prisma.AccidentUpsertWithWhereUniqueWithoutTenantInput | Prisma.AccidentUpsertWithWhereUniqueWithoutTenantInput[]
  createMany?: Prisma.AccidentCreateManyTenantInputEnvelope
  set?: Prisma.AccidentWhereUniqueInput | Prisma.AccidentWhereUniqueInput[]
  disconnect?: Prisma.AccidentWhereUniqueInput | Prisma.AccidentWhereUniqueInput[]
  delete?: Prisma.AccidentWhereUniqueInput | Prisma.AccidentWhereUniqueInput[]
  connect?: Prisma.AccidentWhereUniqueInput | Prisma.AccidentWhereUniqueInput[]
  update?: Prisma.AccidentUpdateWithWhereUniqueWithoutTenantInput | Prisma.AccidentUpdateWithWhereUniqueWithoutTenantInput[]
  updateMany?: Prisma.AccidentUpdateManyWithWhereWithoutTenantInput | Prisma.AccidentUpdateManyWithWhereWithoutTenantInput[]
  deleteMany?: Prisma.AccidentScalarWhereInput | Prisma.AccidentScalarWhereInput[]
}

export type AccidentCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.AccidentCreateWithoutUserInput, Prisma.AccidentUncheckedCreateWithoutUserInput> | Prisma.AccidentCreateWithoutUserInput[] | Prisma.AccidentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AccidentCreateOrConnectWithoutUserInput | Prisma.AccidentCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.AccidentCreateManyUserInputEnvelope
  connect?: Prisma.AccidentWhereUniqueInput | Prisma.AccidentWhereUniqueInput[]
}

export type AccidentUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.AccidentCreateWithoutUserInput, Prisma.AccidentUncheckedCreateWithoutUserInput> | Prisma.AccidentCreateWithoutUserInput[] | Prisma.AccidentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AccidentCreateOrConnectWithoutUserInput | Prisma.AccidentCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.AccidentCreateManyUserInputEnvelope
  connect?: Prisma.AccidentWhereUniqueInput | Prisma.AccidentWhereUniqueInput[]
}

export type AccidentUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.AccidentCreateWithoutUserInput, Prisma.AccidentUncheckedCreateWithoutUserInput> | Prisma.AccidentCreateWithoutUserInput[] | Prisma.AccidentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AccidentCreateOrConnectWithoutUserInput | Prisma.AccidentCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.AccidentUpsertWithWhereUniqueWithoutUserInput | Prisma.AccidentUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.AccidentCreateManyUserInputEnvelope
  set?: Prisma.AccidentWhereUniqueInput | Prisma.AccidentWhereUniqueInput[]
  disconnect?: Prisma.AccidentWhereUniqueInput | Prisma.AccidentWhereUniqueInput[]
  delete?: Prisma.AccidentWhereUniqueInput | Prisma.AccidentWhereUniqueInput[]
  connect?: Prisma.AccidentWhereUniqueInput | Prisma.AccidentWhereUniqueInput[]
  update?: Prisma.AccidentUpdateWithWhereUniqueWithoutUserInput | Prisma.AccidentUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.AccidentUpdateManyWithWhereWithoutUserInput | Prisma.AccidentUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.AccidentScalarWhereInput | Prisma.AccidentScalarWhereInput[]
}

export type AccidentUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.AccidentCreateWithoutUserInput, Prisma.AccidentUncheckedCreateWithoutUserInput> | Prisma.AccidentCreateWithoutUserInput[] | Prisma.AccidentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AccidentCreateOrConnectWithoutUserInput | Prisma.AccidentCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.AccidentUpsertWithWhereUniqueWithoutUserInput | Prisma.AccidentUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.AccidentCreateManyUserInputEnvelope
  set?: Prisma.AccidentWhereUniqueInput | Prisma.AccidentWhereUniqueInput[]
  disconnect?: Prisma.AccidentWhereUniqueInput | Prisma.AccidentWhereUniqueInput[]
  delete?: Prisma.AccidentWhereUniqueInput | Prisma.AccidentWhereUniqueInput[]
  connect?: Prisma.AccidentWhereUniqueInput | Prisma.AccidentWhereUniqueInput[]
  update?: Prisma.AccidentUpdateWithWhereUniqueWithoutUserInput | Prisma.AccidentUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.AccidentUpdateManyWithWhereWithoutUserInput | Prisma.AccidentUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.AccidentScalarWhereInput | Prisma.AccidentScalarWhereInput[]
}

export type DecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type AccidentCreateNestedOneWithoutPhotosInput = {
  create?: Prisma.XOR<Prisma.AccidentCreateWithoutPhotosInput, Prisma.AccidentUncheckedCreateWithoutPhotosInput>
  connectOrCreate?: Prisma.AccidentCreateOrConnectWithoutPhotosInput
  connect?: Prisma.AccidentWhereUniqueInput
}

export type AccidentUpdateOneRequiredWithoutPhotosNestedInput = {
  create?: Prisma.XOR<Prisma.AccidentCreateWithoutPhotosInput, Prisma.AccidentUncheckedCreateWithoutPhotosInput>
  connectOrCreate?: Prisma.AccidentCreateOrConnectWithoutPhotosInput
  upsert?: Prisma.AccidentUpsertWithoutPhotosInput
  connect?: Prisma.AccidentWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AccidentUpdateToOneWithWhereWithoutPhotosInput, Prisma.AccidentUpdateWithoutPhotosInput>, Prisma.AccidentUncheckedUpdateWithoutPhotosInput>
}

export type AccidentCreateWithoutTenantInput = {
  id?: string
  fullName: string
  lastName: string
  locationLat: runtime.Decimal | runtime.DecimalJsLike | number | string
  locationLng: runtime.Decimal | runtime.DecimalJsLike | number | string
  addressText: string
  accidentType: string
  sceneData: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutAccidentsInput
  photos?: Prisma.AccidentPhotoCreateNestedManyWithoutAccidentInput
}

export type AccidentUncheckedCreateWithoutTenantInput = {
  id?: string
  userId: string
  fullName: string
  lastName: string
  locationLat: runtime.Decimal | runtime.DecimalJsLike | number | string
  locationLng: runtime.Decimal | runtime.DecimalJsLike | number | string
  addressText: string
  accidentType: string
  sceneData: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  photos?: Prisma.AccidentPhotoUncheckedCreateNestedManyWithoutAccidentInput
}

export type AccidentCreateOrConnectWithoutTenantInput = {
  where: Prisma.AccidentWhereUniqueInput
  create: Prisma.XOR<Prisma.AccidentCreateWithoutTenantInput, Prisma.AccidentUncheckedCreateWithoutTenantInput>
}

export type AccidentCreateManyTenantInputEnvelope = {
  data: Prisma.AccidentCreateManyTenantInput | Prisma.AccidentCreateManyTenantInput[]
  skipDuplicates?: boolean
}

export type AccidentUpsertWithWhereUniqueWithoutTenantInput = {
  where: Prisma.AccidentWhereUniqueInput
  update: Prisma.XOR<Prisma.AccidentUpdateWithoutTenantInput, Prisma.AccidentUncheckedUpdateWithoutTenantInput>
  create: Prisma.XOR<Prisma.AccidentCreateWithoutTenantInput, Prisma.AccidentUncheckedCreateWithoutTenantInput>
}

export type AccidentUpdateWithWhereUniqueWithoutTenantInput = {
  where: Prisma.AccidentWhereUniqueInput
  data: Prisma.XOR<Prisma.AccidentUpdateWithoutTenantInput, Prisma.AccidentUncheckedUpdateWithoutTenantInput>
}

export type AccidentUpdateManyWithWhereWithoutTenantInput = {
  where: Prisma.AccidentScalarWhereInput
  data: Prisma.XOR<Prisma.AccidentUpdateManyMutationInput, Prisma.AccidentUncheckedUpdateManyWithoutTenantInput>
}

export type AccidentScalarWhereInput = {
  AND?: Prisma.AccidentScalarWhereInput | Prisma.AccidentScalarWhereInput[]
  OR?: Prisma.AccidentScalarWhereInput[]
  NOT?: Prisma.AccidentScalarWhereInput | Prisma.AccidentScalarWhereInput[]
  id?: Prisma.StringFilter<"Accident"> | string
  tenantId?: Prisma.StringFilter<"Accident"> | string
  userId?: Prisma.StringFilter<"Accident"> | string
  fullName?: Prisma.StringFilter<"Accident"> | string
  lastName?: Prisma.StringFilter<"Accident"> | string
  locationLat?: Prisma.DecimalFilter<"Accident"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  locationLng?: Prisma.DecimalFilter<"Accident"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  addressText?: Prisma.StringFilter<"Accident"> | string
  accidentType?: Prisma.StringFilter<"Accident"> | string
  sceneData?: Prisma.JsonFilter<"Accident">
  createdAt?: Prisma.DateTimeFilter<"Accident"> | Date | string
}

export type AccidentCreateWithoutUserInput = {
  id?: string
  fullName: string
  lastName: string
  locationLat: runtime.Decimal | runtime.DecimalJsLike | number | string
  locationLng: runtime.Decimal | runtime.DecimalJsLike | number | string
  addressText: string
  accidentType: string
  sceneData: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  tenant: Prisma.TenantCreateNestedOneWithoutAccidentsInput
  photos?: Prisma.AccidentPhotoCreateNestedManyWithoutAccidentInput
}

export type AccidentUncheckedCreateWithoutUserInput = {
  id?: string
  tenantId: string
  fullName: string
  lastName: string
  locationLat: runtime.Decimal | runtime.DecimalJsLike | number | string
  locationLng: runtime.Decimal | runtime.DecimalJsLike | number | string
  addressText: string
  accidentType: string
  sceneData: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  photos?: Prisma.AccidentPhotoUncheckedCreateNestedManyWithoutAccidentInput
}

export type AccidentCreateOrConnectWithoutUserInput = {
  where: Prisma.AccidentWhereUniqueInput
  create: Prisma.XOR<Prisma.AccidentCreateWithoutUserInput, Prisma.AccidentUncheckedCreateWithoutUserInput>
}

export type AccidentCreateManyUserInputEnvelope = {
  data: Prisma.AccidentCreateManyUserInput | Prisma.AccidentCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type AccidentUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.AccidentWhereUniqueInput
  update: Prisma.XOR<Prisma.AccidentUpdateWithoutUserInput, Prisma.AccidentUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.AccidentCreateWithoutUserInput, Prisma.AccidentUncheckedCreateWithoutUserInput>
}

export type AccidentUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.AccidentWhereUniqueInput
  data: Prisma.XOR<Prisma.AccidentUpdateWithoutUserInput, Prisma.AccidentUncheckedUpdateWithoutUserInput>
}

export type AccidentUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.AccidentScalarWhereInput
  data: Prisma.XOR<Prisma.AccidentUpdateManyMutationInput, Prisma.AccidentUncheckedUpdateManyWithoutUserInput>
}

export type AccidentCreateWithoutPhotosInput = {
  id?: string
  fullName: string
  lastName: string
  locationLat: runtime.Decimal | runtime.DecimalJsLike | number | string
  locationLng: runtime.Decimal | runtime.DecimalJsLike | number | string
  addressText: string
  accidentType: string
  sceneData: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  tenant: Prisma.TenantCreateNestedOneWithoutAccidentsInput
  user: Prisma.UserCreateNestedOneWithoutAccidentsInput
}

export type AccidentUncheckedCreateWithoutPhotosInput = {
  id?: string
  tenantId: string
  userId: string
  fullName: string
  lastName: string
  locationLat: runtime.Decimal | runtime.DecimalJsLike | number | string
  locationLng: runtime.Decimal | runtime.DecimalJsLike | number | string
  addressText: string
  accidentType: string
  sceneData: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type AccidentCreateOrConnectWithoutPhotosInput = {
  where: Prisma.AccidentWhereUniqueInput
  create: Prisma.XOR<Prisma.AccidentCreateWithoutPhotosInput, Prisma.AccidentUncheckedCreateWithoutPhotosInput>
}

export type AccidentUpsertWithoutPhotosInput = {
  update: Prisma.XOR<Prisma.AccidentUpdateWithoutPhotosInput, Prisma.AccidentUncheckedUpdateWithoutPhotosInput>
  create: Prisma.XOR<Prisma.AccidentCreateWithoutPhotosInput, Prisma.AccidentUncheckedCreateWithoutPhotosInput>
  where?: Prisma.AccidentWhereInput
}

export type AccidentUpdateToOneWithWhereWithoutPhotosInput = {
  where?: Prisma.AccidentWhereInput
  data: Prisma.XOR<Prisma.AccidentUpdateWithoutPhotosInput, Prisma.AccidentUncheckedUpdateWithoutPhotosInput>
}

export type AccidentUpdateWithoutPhotosInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  locationLat?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  locationLng?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  addressText?: Prisma.StringFieldUpdateOperationsInput | string
  accidentType?: Prisma.StringFieldUpdateOperationsInput | string
  sceneData?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tenant?: Prisma.TenantUpdateOneRequiredWithoutAccidentsNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutAccidentsNestedInput
}

export type AccidentUncheckedUpdateWithoutPhotosInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  locationLat?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  locationLng?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  addressText?: Prisma.StringFieldUpdateOperationsInput | string
  accidentType?: Prisma.StringFieldUpdateOperationsInput | string
  sceneData?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AccidentCreateManyTenantInput = {
  id?: string
  userId: string
  fullName: string
  lastName: string
  locationLat: runtime.Decimal | runtime.DecimalJsLike | number | string
  locationLng: runtime.Decimal | runtime.DecimalJsLike | number | string
  addressText: string
  accidentType: string
  sceneData: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type AccidentUpdateWithoutTenantInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  locationLat?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  locationLng?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  addressText?: Prisma.StringFieldUpdateOperationsInput | string
  accidentType?: Prisma.StringFieldUpdateOperationsInput | string
  sceneData?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutAccidentsNestedInput
  photos?: Prisma.AccidentPhotoUpdateManyWithoutAccidentNestedInput
}

export type AccidentUncheckedUpdateWithoutTenantInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  locationLat?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  locationLng?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  addressText?: Prisma.StringFieldUpdateOperationsInput | string
  accidentType?: Prisma.StringFieldUpdateOperationsInput | string
  sceneData?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  photos?: Prisma.AccidentPhotoUncheckedUpdateManyWithoutAccidentNestedInput
}

export type AccidentUncheckedUpdateManyWithoutTenantInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  locationLat?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  locationLng?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  addressText?: Prisma.StringFieldUpdateOperationsInput | string
  accidentType?: Prisma.StringFieldUpdateOperationsInput | string
  sceneData?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AccidentCreateManyUserInput = {
  id?: string
  tenantId: string
  fullName: string
  lastName: string
  locationLat: runtime.Decimal | runtime.DecimalJsLike | number | string
  locationLng: runtime.Decimal | runtime.DecimalJsLike | number | string
  addressText: string
  accidentType: string
  sceneData: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type AccidentUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  locationLat?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  locationLng?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  addressText?: Prisma.StringFieldUpdateOperationsInput | string
  accidentType?: Prisma.StringFieldUpdateOperationsInput | string
  sceneData?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tenant?: Prisma.TenantUpdateOneRequiredWithoutAccidentsNestedInput
  photos?: Prisma.AccidentPhotoUpdateManyWithoutAccidentNestedInput
}

export type AccidentUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  locationLat?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  locationLng?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  addressText?: Prisma.StringFieldUpdateOperationsInput | string
  accidentType?: Prisma.StringFieldUpdateOperationsInput | string
  sceneData?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  photos?: Prisma.AccidentPhotoUncheckedUpdateManyWithoutAccidentNestedInput
}

export type AccidentUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  locationLat?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  locationLng?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  addressText?: Prisma.StringFieldUpdateOperationsInput | string
  accidentType?: Prisma.StringFieldUpdateOperationsInput | string
  sceneData?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type AccidentCountOutputType
 */

export type AccidentCountOutputType = {
  photos: number
}

export type AccidentCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  photos?: boolean | AccidentCountOutputTypeCountPhotosArgs
}

/**
 * AccidentCountOutputType without action
 */
export type AccidentCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccidentCountOutputType
   */
  select?: Prisma.AccidentCountOutputTypeSelect<ExtArgs> | null
}

/**
 * AccidentCountOutputType without action
 */
export type AccidentCountOutputTypeCountPhotosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AccidentPhotoWhereInput
}


export type AccidentSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tenantId?: boolean
  userId?: boolean
  fullName?: boolean
  lastName?: boolean
  locationLat?: boolean
  locationLng?: boolean
  addressText?: boolean
  accidentType?: boolean
  sceneData?: boolean
  createdAt?: boolean
  tenant?: boolean | Prisma.TenantDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  photos?: boolean | Prisma.Accident$photosArgs<ExtArgs>
  _count?: boolean | Prisma.AccidentCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["accident"]>

export type AccidentSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tenantId?: boolean
  userId?: boolean
  fullName?: boolean
  lastName?: boolean
  locationLat?: boolean
  locationLng?: boolean
  addressText?: boolean
  accidentType?: boolean
  sceneData?: boolean
  createdAt?: boolean
  tenant?: boolean | Prisma.TenantDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["accident"]>

export type AccidentSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tenantId?: boolean
  userId?: boolean
  fullName?: boolean
  lastName?: boolean
  locationLat?: boolean
  locationLng?: boolean
  addressText?: boolean
  accidentType?: boolean
  sceneData?: boolean
  createdAt?: boolean
  tenant?: boolean | Prisma.TenantDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["accident"]>

export type AccidentSelectScalar = {
  id?: boolean
  tenantId?: boolean
  userId?: boolean
  fullName?: boolean
  lastName?: boolean
  locationLat?: boolean
  locationLng?: boolean
  addressText?: boolean
  accidentType?: boolean
  sceneData?: boolean
  createdAt?: boolean
}

export type AccidentOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "tenantId" | "userId" | "fullName" | "lastName" | "locationLat" | "locationLng" | "addressText" | "accidentType" | "sceneData" | "createdAt", ExtArgs["result"]["accident"]>
export type AccidentInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tenant?: boolean | Prisma.TenantDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  photos?: boolean | Prisma.Accident$photosArgs<ExtArgs>
  _count?: boolean | Prisma.AccidentCountOutputTypeDefaultArgs<ExtArgs>
}
export type AccidentIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tenant?: boolean | Prisma.TenantDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type AccidentIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tenant?: boolean | Prisma.TenantDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $AccidentPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Accident"
  objects: {
    tenant: Prisma.$TenantPayload<ExtArgs>
    user: Prisma.$UserPayload<ExtArgs>
    photos: Prisma.$AccidentPhotoPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    tenantId: string
    userId: string
    fullName: string
    lastName: string
    locationLat: runtime.Decimal
    locationLng: runtime.Decimal
    addressText: string
    accidentType: string
    sceneData: runtime.JsonValue
    createdAt: Date
  }, ExtArgs["result"]["accident"]>
  composites: {}
}

export type AccidentGetPayload<S extends boolean | null | undefined | AccidentDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AccidentPayload, S>

export type AccidentCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AccidentFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AccidentCountAggregateInputType | true
  }

export interface AccidentDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Accident'], meta: { name: 'Accident' } }
  /**
   * Find zero or one Accident that matches the filter.
   * @param {AccidentFindUniqueArgs} args - Arguments to find a Accident
   * @example
   * // Get one Accident
   * const accident = await prisma.accident.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AccidentFindUniqueArgs>(args: Prisma.SelectSubset<T, AccidentFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AccidentClient<runtime.Types.Result.GetResult<Prisma.$AccidentPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Accident that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AccidentFindUniqueOrThrowArgs} args - Arguments to find a Accident
   * @example
   * // Get one Accident
   * const accident = await prisma.accident.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AccidentFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AccidentFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AccidentClient<runtime.Types.Result.GetResult<Prisma.$AccidentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Accident that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccidentFindFirstArgs} args - Arguments to find a Accident
   * @example
   * // Get one Accident
   * const accident = await prisma.accident.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AccidentFindFirstArgs>(args?: Prisma.SelectSubset<T, AccidentFindFirstArgs<ExtArgs>>): Prisma.Prisma__AccidentClient<runtime.Types.Result.GetResult<Prisma.$AccidentPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Accident that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccidentFindFirstOrThrowArgs} args - Arguments to find a Accident
   * @example
   * // Get one Accident
   * const accident = await prisma.accident.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AccidentFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AccidentFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AccidentClient<runtime.Types.Result.GetResult<Prisma.$AccidentPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Accidents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccidentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Accidents
   * const accidents = await prisma.accident.findMany()
   * 
   * // Get first 10 Accidents
   * const accidents = await prisma.accident.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const accidentWithIdOnly = await prisma.accident.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AccidentFindManyArgs>(args?: Prisma.SelectSubset<T, AccidentFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccidentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Accident.
   * @param {AccidentCreateArgs} args - Arguments to create a Accident.
   * @example
   * // Create one Accident
   * const Accident = await prisma.accident.create({
   *   data: {
   *     // ... data to create a Accident
   *   }
   * })
   * 
   */
  create<T extends AccidentCreateArgs>(args: Prisma.SelectSubset<T, AccidentCreateArgs<ExtArgs>>): Prisma.Prisma__AccidentClient<runtime.Types.Result.GetResult<Prisma.$AccidentPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Accidents.
   * @param {AccidentCreateManyArgs} args - Arguments to create many Accidents.
   * @example
   * // Create many Accidents
   * const accident = await prisma.accident.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AccidentCreateManyArgs>(args?: Prisma.SelectSubset<T, AccidentCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Accidents and returns the data saved in the database.
   * @param {AccidentCreateManyAndReturnArgs} args - Arguments to create many Accidents.
   * @example
   * // Create many Accidents
   * const accident = await prisma.accident.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Accidents and only return the `id`
   * const accidentWithIdOnly = await prisma.accident.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AccidentCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AccidentCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccidentPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Accident.
   * @param {AccidentDeleteArgs} args - Arguments to delete one Accident.
   * @example
   * // Delete one Accident
   * const Accident = await prisma.accident.delete({
   *   where: {
   *     // ... filter to delete one Accident
   *   }
   * })
   * 
   */
  delete<T extends AccidentDeleteArgs>(args: Prisma.SelectSubset<T, AccidentDeleteArgs<ExtArgs>>): Prisma.Prisma__AccidentClient<runtime.Types.Result.GetResult<Prisma.$AccidentPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Accident.
   * @param {AccidentUpdateArgs} args - Arguments to update one Accident.
   * @example
   * // Update one Accident
   * const accident = await prisma.accident.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AccidentUpdateArgs>(args: Prisma.SelectSubset<T, AccidentUpdateArgs<ExtArgs>>): Prisma.Prisma__AccidentClient<runtime.Types.Result.GetResult<Prisma.$AccidentPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Accidents.
   * @param {AccidentDeleteManyArgs} args - Arguments to filter Accidents to delete.
   * @example
   * // Delete a few Accidents
   * const { count } = await prisma.accident.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AccidentDeleteManyArgs>(args?: Prisma.SelectSubset<T, AccidentDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Accidents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccidentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Accidents
   * const accident = await prisma.accident.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AccidentUpdateManyArgs>(args: Prisma.SelectSubset<T, AccidentUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Accidents and returns the data updated in the database.
   * @param {AccidentUpdateManyAndReturnArgs} args - Arguments to update many Accidents.
   * @example
   * // Update many Accidents
   * const accident = await prisma.accident.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Accidents and only return the `id`
   * const accidentWithIdOnly = await prisma.accident.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AccidentUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AccidentUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccidentPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Accident.
   * @param {AccidentUpsertArgs} args - Arguments to update or create a Accident.
   * @example
   * // Update or create a Accident
   * const accident = await prisma.accident.upsert({
   *   create: {
   *     // ... data to create a Accident
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Accident we want to update
   *   }
   * })
   */
  upsert<T extends AccidentUpsertArgs>(args: Prisma.SelectSubset<T, AccidentUpsertArgs<ExtArgs>>): Prisma.Prisma__AccidentClient<runtime.Types.Result.GetResult<Prisma.$AccidentPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Accidents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccidentCountArgs} args - Arguments to filter Accidents to count.
   * @example
   * // Count the number of Accidents
   * const count = await prisma.accident.count({
   *   where: {
   *     // ... the filter for the Accidents we want to count
   *   }
   * })
  **/
  count<T extends AccidentCountArgs>(
    args?: Prisma.Subset<T, AccidentCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AccidentCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Accident.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccidentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AccidentAggregateArgs>(args: Prisma.Subset<T, AccidentAggregateArgs>): Prisma.PrismaPromise<GetAccidentAggregateType<T>>

  /**
   * Group by Accident.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccidentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AccidentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AccidentGroupByArgs['orderBy'] }
      : { orderBy?: AccidentGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AccidentGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAccidentGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Accident model
 */
readonly fields: AccidentFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Accident.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AccidentClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  tenant<T extends Prisma.TenantDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TenantDefaultArgs<ExtArgs>>): Prisma.Prisma__TenantClient<runtime.Types.Result.GetResult<Prisma.$TenantPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  photos<T extends Prisma.Accident$photosArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Accident$photosArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccidentPhotoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Accident model
 */
export interface AccidentFieldRefs {
  readonly id: Prisma.FieldRef<"Accident", 'String'>
  readonly tenantId: Prisma.FieldRef<"Accident", 'String'>
  readonly userId: Prisma.FieldRef<"Accident", 'String'>
  readonly fullName: Prisma.FieldRef<"Accident", 'String'>
  readonly lastName: Prisma.FieldRef<"Accident", 'String'>
  readonly locationLat: Prisma.FieldRef<"Accident", 'Decimal'>
  readonly locationLng: Prisma.FieldRef<"Accident", 'Decimal'>
  readonly addressText: Prisma.FieldRef<"Accident", 'String'>
  readonly accidentType: Prisma.FieldRef<"Accident", 'String'>
  readonly sceneData: Prisma.FieldRef<"Accident", 'Json'>
  readonly createdAt: Prisma.FieldRef<"Accident", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Accident findUnique
 */
export type AccidentFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Accident
   */
  select?: Prisma.AccidentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Accident
   */
  omit?: Prisma.AccidentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccidentInclude<ExtArgs> | null
  /**
   * Filter, which Accident to fetch.
   */
  where: Prisma.AccidentWhereUniqueInput
}

/**
 * Accident findUniqueOrThrow
 */
export type AccidentFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Accident
   */
  select?: Prisma.AccidentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Accident
   */
  omit?: Prisma.AccidentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccidentInclude<ExtArgs> | null
  /**
   * Filter, which Accident to fetch.
   */
  where: Prisma.AccidentWhereUniqueInput
}

/**
 * Accident findFirst
 */
export type AccidentFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Accident
   */
  select?: Prisma.AccidentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Accident
   */
  omit?: Prisma.AccidentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccidentInclude<ExtArgs> | null
  /**
   * Filter, which Accident to fetch.
   */
  where?: Prisma.AccidentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Accidents to fetch.
   */
  orderBy?: Prisma.AccidentOrderByWithRelationInput | Prisma.AccidentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Accidents.
   */
  cursor?: Prisma.AccidentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Accidents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Accidents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Accidents.
   */
  distinct?: Prisma.AccidentScalarFieldEnum | Prisma.AccidentScalarFieldEnum[]
}

/**
 * Accident findFirstOrThrow
 */
export type AccidentFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Accident
   */
  select?: Prisma.AccidentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Accident
   */
  omit?: Prisma.AccidentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccidentInclude<ExtArgs> | null
  /**
   * Filter, which Accident to fetch.
   */
  where?: Prisma.AccidentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Accidents to fetch.
   */
  orderBy?: Prisma.AccidentOrderByWithRelationInput | Prisma.AccidentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Accidents.
   */
  cursor?: Prisma.AccidentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Accidents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Accidents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Accidents.
   */
  distinct?: Prisma.AccidentScalarFieldEnum | Prisma.AccidentScalarFieldEnum[]
}

/**
 * Accident findMany
 */
export type AccidentFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Accident
   */
  select?: Prisma.AccidentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Accident
   */
  omit?: Prisma.AccidentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccidentInclude<ExtArgs> | null
  /**
   * Filter, which Accidents to fetch.
   */
  where?: Prisma.AccidentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Accidents to fetch.
   */
  orderBy?: Prisma.AccidentOrderByWithRelationInput | Prisma.AccidentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Accidents.
   */
  cursor?: Prisma.AccidentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Accidents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Accidents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Accidents.
   */
  distinct?: Prisma.AccidentScalarFieldEnum | Prisma.AccidentScalarFieldEnum[]
}

/**
 * Accident create
 */
export type AccidentCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Accident
   */
  select?: Prisma.AccidentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Accident
   */
  omit?: Prisma.AccidentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccidentInclude<ExtArgs> | null
  /**
   * The data needed to create a Accident.
   */
  data: Prisma.XOR<Prisma.AccidentCreateInput, Prisma.AccidentUncheckedCreateInput>
}

/**
 * Accident createMany
 */
export type AccidentCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Accidents.
   */
  data: Prisma.AccidentCreateManyInput | Prisma.AccidentCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Accident createManyAndReturn
 */
export type AccidentCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Accident
   */
  select?: Prisma.AccidentSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Accident
   */
  omit?: Prisma.AccidentOmit<ExtArgs> | null
  /**
   * The data used to create many Accidents.
   */
  data: Prisma.AccidentCreateManyInput | Prisma.AccidentCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccidentIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Accident update
 */
export type AccidentUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Accident
   */
  select?: Prisma.AccidentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Accident
   */
  omit?: Prisma.AccidentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccidentInclude<ExtArgs> | null
  /**
   * The data needed to update a Accident.
   */
  data: Prisma.XOR<Prisma.AccidentUpdateInput, Prisma.AccidentUncheckedUpdateInput>
  /**
   * Choose, which Accident to update.
   */
  where: Prisma.AccidentWhereUniqueInput
}

/**
 * Accident updateMany
 */
export type AccidentUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Accidents.
   */
  data: Prisma.XOR<Prisma.AccidentUpdateManyMutationInput, Prisma.AccidentUncheckedUpdateManyInput>
  /**
   * Filter which Accidents to update
   */
  where?: Prisma.AccidentWhereInput
  /**
   * Limit how many Accidents to update.
   */
  limit?: number
}

/**
 * Accident updateManyAndReturn
 */
export type AccidentUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Accident
   */
  select?: Prisma.AccidentSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Accident
   */
  omit?: Prisma.AccidentOmit<ExtArgs> | null
  /**
   * The data used to update Accidents.
   */
  data: Prisma.XOR<Prisma.AccidentUpdateManyMutationInput, Prisma.AccidentUncheckedUpdateManyInput>
  /**
   * Filter which Accidents to update
   */
  where?: Prisma.AccidentWhereInput
  /**
   * Limit how many Accidents to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccidentIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Accident upsert
 */
export type AccidentUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Accident
   */
  select?: Prisma.AccidentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Accident
   */
  omit?: Prisma.AccidentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccidentInclude<ExtArgs> | null
  /**
   * The filter to search for the Accident to update in case it exists.
   */
  where: Prisma.AccidentWhereUniqueInput
  /**
   * In case the Accident found by the `where` argument doesn't exist, create a new Accident with this data.
   */
  create: Prisma.XOR<Prisma.AccidentCreateInput, Prisma.AccidentUncheckedCreateInput>
  /**
   * In case the Accident was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AccidentUpdateInput, Prisma.AccidentUncheckedUpdateInput>
}

/**
 * Accident delete
 */
export type AccidentDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Accident
   */
  select?: Prisma.AccidentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Accident
   */
  omit?: Prisma.AccidentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccidentInclude<ExtArgs> | null
  /**
   * Filter which Accident to delete.
   */
  where: Prisma.AccidentWhereUniqueInput
}

/**
 * Accident deleteMany
 */
export type AccidentDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Accidents to delete
   */
  where?: Prisma.AccidentWhereInput
  /**
   * Limit how many Accidents to delete.
   */
  limit?: number
}

/**
 * Accident.photos
 */
export type Accident$photosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccidentPhoto
   */
  select?: Prisma.AccidentPhotoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccidentPhoto
   */
  omit?: Prisma.AccidentPhotoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccidentPhotoInclude<ExtArgs> | null
  where?: Prisma.AccidentPhotoWhereInput
  orderBy?: Prisma.AccidentPhotoOrderByWithRelationInput | Prisma.AccidentPhotoOrderByWithRelationInput[]
  cursor?: Prisma.AccidentPhotoWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AccidentPhotoScalarFieldEnum | Prisma.AccidentPhotoScalarFieldEnum[]
}

/**
 * Accident without action
 */
export type AccidentDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Accident
   */
  select?: Prisma.AccidentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Accident
   */
  omit?: Prisma.AccidentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccidentInclude<ExtArgs> | null
}
