
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AccidentPhoto` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model AccidentPhoto
 * 
 */
export type AccidentPhotoModel = runtime.Types.Result.DefaultSelection<Prisma.$AccidentPhotoPayload>

export type AggregateAccidentPhoto = {
  _count: AccidentPhotoCountAggregateOutputType | null
  _min: AccidentPhotoMinAggregateOutputType | null
  _max: AccidentPhotoMaxAggregateOutputType | null
}

export type AccidentPhotoMinAggregateOutputType = {
  id: string | null
  accidentId: string | null
  url: string | null
  createdAt: Date | null
}

export type AccidentPhotoMaxAggregateOutputType = {
  id: string | null
  accidentId: string | null
  url: string | null
  createdAt: Date | null
}

export type AccidentPhotoCountAggregateOutputType = {
  id: number
  accidentId: number
  url: number
  createdAt: number
  _all: number
}


export type AccidentPhotoMinAggregateInputType = {
  id?: true
  accidentId?: true
  url?: true
  createdAt?: true
}

export type AccidentPhotoMaxAggregateInputType = {
  id?: true
  accidentId?: true
  url?: true
  createdAt?: true
}

export type AccidentPhotoCountAggregateInputType = {
  id?: true
  accidentId?: true
  url?: true
  createdAt?: true
  _all?: true
}

export type AccidentPhotoAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AccidentPhoto to aggregate.
   */
  where?: Prisma.AccidentPhotoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AccidentPhotos to fetch.
   */
  orderBy?: Prisma.AccidentPhotoOrderByWithRelationInput | Prisma.AccidentPhotoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AccidentPhotoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AccidentPhotos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AccidentPhotos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AccidentPhotos
  **/
  _count?: true | AccidentPhotoCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AccidentPhotoMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AccidentPhotoMaxAggregateInputType
}

export type GetAccidentPhotoAggregateType<T extends AccidentPhotoAggregateArgs> = {
      [P in keyof T & keyof AggregateAccidentPhoto]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAccidentPhoto[P]>
    : Prisma.GetScalarType<T[P], AggregateAccidentPhoto[P]>
}




export type AccidentPhotoGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AccidentPhotoWhereInput
  orderBy?: Prisma.AccidentPhotoOrderByWithAggregationInput | Prisma.AccidentPhotoOrderByWithAggregationInput[]
  by: Prisma.AccidentPhotoScalarFieldEnum[] | Prisma.AccidentPhotoScalarFieldEnum
  having?: Prisma.AccidentPhotoScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AccidentPhotoCountAggregateInputType | true
  _min?: AccidentPhotoMinAggregateInputType
  _max?: AccidentPhotoMaxAggregateInputType
}

export type AccidentPhotoGroupByOutputType = {
  id: string
  accidentId: string
  url: string
  createdAt: Date
  _count: AccidentPhotoCountAggregateOutputType | null
  _min: AccidentPhotoMinAggregateOutputType | null
  _max: AccidentPhotoMaxAggregateOutputType | null
}

export type GetAccidentPhotoGroupByPayload<T extends AccidentPhotoGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AccidentPhotoGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AccidentPhotoGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AccidentPhotoGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AccidentPhotoGroupByOutputType[P]>
      }
    >
  >



export type AccidentPhotoWhereInput = {
  AND?: Prisma.AccidentPhotoWhereInput | Prisma.AccidentPhotoWhereInput[]
  OR?: Prisma.AccidentPhotoWhereInput[]
  NOT?: Prisma.AccidentPhotoWhereInput | Prisma.AccidentPhotoWhereInput[]
  id?: Prisma.StringFilter<"AccidentPhoto"> | string
  accidentId?: Prisma.StringFilter<"AccidentPhoto"> | string
  url?: Prisma.StringFilter<"AccidentPhoto"> | string
  createdAt?: Prisma.DateTimeFilter<"AccidentPhoto"> | Date | string
  accident?: Prisma.XOR<Prisma.AccidentScalarRelationFilter, Prisma.AccidentWhereInput>
}

export type AccidentPhotoOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  accidentId?: Prisma.SortOrder
  url?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  accident?: Prisma.AccidentOrderByWithRelationInput
}

export type AccidentPhotoWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.AccidentPhotoWhereInput | Prisma.AccidentPhotoWhereInput[]
  OR?: Prisma.AccidentPhotoWhereInput[]
  NOT?: Prisma.AccidentPhotoWhereInput | Prisma.AccidentPhotoWhereInput[]
  accidentId?: Prisma.StringFilter<"AccidentPhoto"> | string
  url?: Prisma.StringFilter<"AccidentPhoto"> | string
  createdAt?: Prisma.DateTimeFilter<"AccidentPhoto"> | Date | string
  accident?: Prisma.XOR<Prisma.AccidentScalarRelationFilter, Prisma.AccidentWhereInput>
}, "id">

export type AccidentPhotoOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  accidentId?: Prisma.SortOrder
  url?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.AccidentPhotoCountOrderByAggregateInput
  _max?: Prisma.AccidentPhotoMaxOrderByAggregateInput
  _min?: Prisma.AccidentPhotoMinOrderByAggregateInput
}

export type AccidentPhotoScalarWhereWithAggregatesInput = {
  AND?: Prisma.AccidentPhotoScalarWhereWithAggregatesInput | Prisma.AccidentPhotoScalarWhereWithAggregatesInput[]
  OR?: Prisma.AccidentPhotoScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AccidentPhotoScalarWhereWithAggregatesInput | Prisma.AccidentPhotoScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"AccidentPhoto"> | string
  accidentId?: Prisma.StringWithAggregatesFilter<"AccidentPhoto"> | string
  url?: Prisma.StringWithAggregatesFilter<"AccidentPhoto"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"AccidentPhoto"> | Date | string
}

export type AccidentPhotoCreateInput = {
  id?: string
  url: string
  createdAt?: Date | string
  accident: Prisma.AccidentCreateNestedOneWithoutPhotosInput
}

export type AccidentPhotoUncheckedCreateInput = {
  id?: string
  accidentId: string
  url: string
  createdAt?: Date | string
}

export type AccidentPhotoUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  accident?: Prisma.AccidentUpdateOneRequiredWithoutPhotosNestedInput
}

export type AccidentPhotoUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  accidentId?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AccidentPhotoCreateManyInput = {
  id?: string
  accidentId: string
  url: string
  createdAt?: Date | string
}

export type AccidentPhotoUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AccidentPhotoUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  accidentId?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AccidentPhotoListRelationFilter = {
  every?: Prisma.AccidentPhotoWhereInput
  some?: Prisma.AccidentPhotoWhereInput
  none?: Prisma.AccidentPhotoWhereInput
}

export type AccidentPhotoOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AccidentPhotoCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  accidentId?: Prisma.SortOrder
  url?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AccidentPhotoMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  accidentId?: Prisma.SortOrder
  url?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AccidentPhotoMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  accidentId?: Prisma.SortOrder
  url?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AccidentPhotoCreateNestedManyWithoutAccidentInput = {
  create?: Prisma.XOR<Prisma.AccidentPhotoCreateWithoutAccidentInput, Prisma.AccidentPhotoUncheckedCreateWithoutAccidentInput> | Prisma.AccidentPhotoCreateWithoutAccidentInput[] | Prisma.AccidentPhotoUncheckedCreateWithoutAccidentInput[]
  connectOrCreate?: Prisma.AccidentPhotoCreateOrConnectWithoutAccidentInput | Prisma.AccidentPhotoCreateOrConnectWithoutAccidentInput[]
  createMany?: Prisma.AccidentPhotoCreateManyAccidentInputEnvelope
  connect?: Prisma.AccidentPhotoWhereUniqueInput | Prisma.AccidentPhotoWhereUniqueInput[]
}

export type AccidentPhotoUncheckedCreateNestedManyWithoutAccidentInput = {
  create?: Prisma.XOR<Prisma.AccidentPhotoCreateWithoutAccidentInput, Prisma.AccidentPhotoUncheckedCreateWithoutAccidentInput> | Prisma.AccidentPhotoCreateWithoutAccidentInput[] | Prisma.AccidentPhotoUncheckedCreateWithoutAccidentInput[]
  connectOrCreate?: Prisma.AccidentPhotoCreateOrConnectWithoutAccidentInput | Prisma.AccidentPhotoCreateOrConnectWithoutAccidentInput[]
  createMany?: Prisma.AccidentPhotoCreateManyAccidentInputEnvelope
  connect?: Prisma.AccidentPhotoWhereUniqueInput | Prisma.AccidentPhotoWhereUniqueInput[]
}

export type AccidentPhotoUpdateManyWithoutAccidentNestedInput = {
  create?: Prisma.XOR<Prisma.AccidentPhotoCreateWithoutAccidentInput, Prisma.AccidentPhotoUncheckedCreateWithoutAccidentInput> | Prisma.AccidentPhotoCreateWithoutAccidentInput[] | Prisma.AccidentPhotoUncheckedCreateWithoutAccidentInput[]
  connectOrCreate?: Prisma.AccidentPhotoCreateOrConnectWithoutAccidentInput | Prisma.AccidentPhotoCreateOrConnectWithoutAccidentInput[]
  upsert?: Prisma.AccidentPhotoUpsertWithWhereUniqueWithoutAccidentInput | Prisma.AccidentPhotoUpsertWithWhereUniqueWithoutAccidentInput[]
  createMany?: Prisma.AccidentPhotoCreateManyAccidentInputEnvelope
  set?: Prisma.AccidentPhotoWhereUniqueInput | Prisma.AccidentPhotoWhereUniqueInput[]
  disconnect?: Prisma.AccidentPhotoWhereUniqueInput | Prisma.AccidentPhotoWhereUniqueInput[]
  delete?: Prisma.AccidentPhotoWhereUniqueInput | Prisma.AccidentPhotoWhereUniqueInput[]
  connect?: Prisma.AccidentPhotoWhereUniqueInput | Prisma.AccidentPhotoWhereUniqueInput[]
  update?: Prisma.AccidentPhotoUpdateWithWhereUniqueWithoutAccidentInput | Prisma.AccidentPhotoUpdateWithWhereUniqueWithoutAccidentInput[]
  updateMany?: Prisma.AccidentPhotoUpdateManyWithWhereWithoutAccidentInput | Prisma.AccidentPhotoUpdateManyWithWhereWithoutAccidentInput[]
  deleteMany?: Prisma.AccidentPhotoScalarWhereInput | Prisma.AccidentPhotoScalarWhereInput[]
}

export type AccidentPhotoUncheckedUpdateManyWithoutAccidentNestedInput = {
  create?: Prisma.XOR<Prisma.AccidentPhotoCreateWithoutAccidentInput, Prisma.AccidentPhotoUncheckedCreateWithoutAccidentInput> | Prisma.AccidentPhotoCreateWithoutAccidentInput[] | Prisma.AccidentPhotoUncheckedCreateWithoutAccidentInput[]
  connectOrCreate?: Prisma.AccidentPhotoCreateOrConnectWithoutAccidentInput | Prisma.AccidentPhotoCreateOrConnectWithoutAccidentInput[]
  upsert?: Prisma.AccidentPhotoUpsertWithWhereUniqueWithoutAccidentInput | Prisma.AccidentPhotoUpsertWithWhereUniqueWithoutAccidentInput[]
  createMany?: Prisma.AccidentPhotoCreateManyAccidentInputEnvelope
  set?: Prisma.AccidentPhotoWhereUniqueInput | Prisma.AccidentPhotoWhereUniqueInput[]
  disconnect?: Prisma.AccidentPhotoWhereUniqueInput | Prisma.AccidentPhotoWhereUniqueInput[]
  delete?: Prisma.AccidentPhotoWhereUniqueInput | Prisma.AccidentPhotoWhereUniqueInput[]
  connect?: Prisma.AccidentPhotoWhereUniqueInput | Prisma.AccidentPhotoWhereUniqueInput[]
  update?: Prisma.AccidentPhotoUpdateWithWhereUniqueWithoutAccidentInput | Prisma.AccidentPhotoUpdateWithWhereUniqueWithoutAccidentInput[]
  updateMany?: Prisma.AccidentPhotoUpdateManyWithWhereWithoutAccidentInput | Prisma.AccidentPhotoUpdateManyWithWhereWithoutAccidentInput[]
  deleteMany?: Prisma.AccidentPhotoScalarWhereInput | Prisma.AccidentPhotoScalarWhereInput[]
}

export type AccidentPhotoCreateWithoutAccidentInput = {
  id?: string
  url: string
  createdAt?: Date | string
}

export type AccidentPhotoUncheckedCreateWithoutAccidentInput = {
  id?: string
  url: string
  createdAt?: Date | string
}

export type AccidentPhotoCreateOrConnectWithoutAccidentInput = {
  where: Prisma.AccidentPhotoWhereUniqueInput
  create: Prisma.XOR<Prisma.AccidentPhotoCreateWithoutAccidentInput, Prisma.AccidentPhotoUncheckedCreateWithoutAccidentInput>
}

export type AccidentPhotoCreateManyAccidentInputEnvelope = {
  data: Prisma.AccidentPhotoCreateManyAccidentInput | Prisma.AccidentPhotoCreateManyAccidentInput[]
  skipDuplicates?: boolean
}

export type AccidentPhotoUpsertWithWhereUniqueWithoutAccidentInput = {
  where: Prisma.AccidentPhotoWhereUniqueInput
  update: Prisma.XOR<Prisma.AccidentPhotoUpdateWithoutAccidentInput, Prisma.AccidentPhotoUncheckedUpdateWithoutAccidentInput>
  create: Prisma.XOR<Prisma.AccidentPhotoCreateWithoutAccidentInput, Prisma.AccidentPhotoUncheckedCreateWithoutAccidentInput>
}

export type AccidentPhotoUpdateWithWhereUniqueWithoutAccidentInput = {
  where: Prisma.AccidentPhotoWhereUniqueInput
  data: Prisma.XOR<Prisma.AccidentPhotoUpdateWithoutAccidentInput, Prisma.AccidentPhotoUncheckedUpdateWithoutAccidentInput>
}

export type AccidentPhotoUpdateManyWithWhereWithoutAccidentInput = {
  where: Prisma.AccidentPhotoScalarWhereInput
  data: Prisma.XOR<Prisma.AccidentPhotoUpdateManyMutationInput, Prisma.AccidentPhotoUncheckedUpdateManyWithoutAccidentInput>
}

export type AccidentPhotoScalarWhereInput = {
  AND?: Prisma.AccidentPhotoScalarWhereInput | Prisma.AccidentPhotoScalarWhereInput[]
  OR?: Prisma.AccidentPhotoScalarWhereInput[]
  NOT?: Prisma.AccidentPhotoScalarWhereInput | Prisma.AccidentPhotoScalarWhereInput[]
  id?: Prisma.StringFilter<"AccidentPhoto"> | string
  accidentId?: Prisma.StringFilter<"AccidentPhoto"> | string
  url?: Prisma.StringFilter<"AccidentPhoto"> | string
  createdAt?: Prisma.DateTimeFilter<"AccidentPhoto"> | Date | string
}

export type AccidentPhotoCreateManyAccidentInput = {
  id?: string
  url: string
  createdAt?: Date | string
}

export type AccidentPhotoUpdateWithoutAccidentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AccidentPhotoUncheckedUpdateWithoutAccidentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AccidentPhotoUncheckedUpdateManyWithoutAccidentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type AccidentPhotoSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  accidentId?: boolean
  url?: boolean
  createdAt?: boolean
  accident?: boolean | Prisma.AccidentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["accidentPhoto"]>

export type AccidentPhotoSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  accidentId?: boolean
  url?: boolean
  createdAt?: boolean
  accident?: boolean | Prisma.AccidentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["accidentPhoto"]>

export type AccidentPhotoSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  accidentId?: boolean
  url?: boolean
  createdAt?: boolean
  accident?: boolean | Prisma.AccidentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["accidentPhoto"]>

export type AccidentPhotoSelectScalar = {
  id?: boolean
  accidentId?: boolean
  url?: boolean
  createdAt?: boolean
}

export type AccidentPhotoOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "accidentId" | "url" | "createdAt", ExtArgs["result"]["accidentPhoto"]>
export type AccidentPhotoInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  accident?: boolean | Prisma.AccidentDefaultArgs<ExtArgs>
}
export type AccidentPhotoIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  accident?: boolean | Prisma.AccidentDefaultArgs<ExtArgs>
}
export type AccidentPhotoIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  accident?: boolean | Prisma.AccidentDefaultArgs<ExtArgs>
}

export type $AccidentPhotoPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AccidentPhoto"
  objects: {
    accident: Prisma.$AccidentPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    accidentId: string
    url: string
    createdAt: Date
  }, ExtArgs["result"]["accidentPhoto"]>
  composites: {}
}

export type AccidentPhotoGetPayload<S extends boolean | null | undefined | AccidentPhotoDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AccidentPhotoPayload, S>

export type AccidentPhotoCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AccidentPhotoFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AccidentPhotoCountAggregateInputType | true
  }

export interface AccidentPhotoDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AccidentPhoto'], meta: { name: 'AccidentPhoto' } }
  /**
   * Find zero or one AccidentPhoto that matches the filter.
   * @param {AccidentPhotoFindUniqueArgs} args - Arguments to find a AccidentPhoto
   * @example
   * // Get one AccidentPhoto
   * const accidentPhoto = await prisma.accidentPhoto.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AccidentPhotoFindUniqueArgs>(args: Prisma.SelectSubset<T, AccidentPhotoFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AccidentPhotoClient<runtime.Types.Result.GetResult<Prisma.$AccidentPhotoPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AccidentPhoto that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AccidentPhotoFindUniqueOrThrowArgs} args - Arguments to find a AccidentPhoto
   * @example
   * // Get one AccidentPhoto
   * const accidentPhoto = await prisma.accidentPhoto.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AccidentPhotoFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AccidentPhotoFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AccidentPhotoClient<runtime.Types.Result.GetResult<Prisma.$AccidentPhotoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AccidentPhoto that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccidentPhotoFindFirstArgs} args - Arguments to find a AccidentPhoto
   * @example
   * // Get one AccidentPhoto
   * const accidentPhoto = await prisma.accidentPhoto.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AccidentPhotoFindFirstArgs>(args?: Prisma.SelectSubset<T, AccidentPhotoFindFirstArgs<ExtArgs>>): Prisma.Prisma__AccidentPhotoClient<runtime.Types.Result.GetResult<Prisma.$AccidentPhotoPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AccidentPhoto that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccidentPhotoFindFirstOrThrowArgs} args - Arguments to find a AccidentPhoto
   * @example
   * // Get one AccidentPhoto
   * const accidentPhoto = await prisma.accidentPhoto.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AccidentPhotoFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AccidentPhotoFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AccidentPhotoClient<runtime.Types.Result.GetResult<Prisma.$AccidentPhotoPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AccidentPhotos that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccidentPhotoFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AccidentPhotos
   * const accidentPhotos = await prisma.accidentPhoto.findMany()
   * 
   * // Get first 10 AccidentPhotos
   * const accidentPhotos = await prisma.accidentPhoto.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const accidentPhotoWithIdOnly = await prisma.accidentPhoto.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AccidentPhotoFindManyArgs>(args?: Prisma.SelectSubset<T, AccidentPhotoFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccidentPhotoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AccidentPhoto.
   * @param {AccidentPhotoCreateArgs} args - Arguments to create a AccidentPhoto.
   * @example
   * // Create one AccidentPhoto
   * const AccidentPhoto = await prisma.accidentPhoto.create({
   *   data: {
   *     // ... data to create a AccidentPhoto
   *   }
   * })
   * 
   */
  create<T extends AccidentPhotoCreateArgs>(args: Prisma.SelectSubset<T, AccidentPhotoCreateArgs<ExtArgs>>): Prisma.Prisma__AccidentPhotoClient<runtime.Types.Result.GetResult<Prisma.$AccidentPhotoPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AccidentPhotos.
   * @param {AccidentPhotoCreateManyArgs} args - Arguments to create many AccidentPhotos.
   * @example
   * // Create many AccidentPhotos
   * const accidentPhoto = await prisma.accidentPhoto.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AccidentPhotoCreateManyArgs>(args?: Prisma.SelectSubset<T, AccidentPhotoCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AccidentPhotos and returns the data saved in the database.
   * @param {AccidentPhotoCreateManyAndReturnArgs} args - Arguments to create many AccidentPhotos.
   * @example
   * // Create many AccidentPhotos
   * const accidentPhoto = await prisma.accidentPhoto.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AccidentPhotos and only return the `id`
   * const accidentPhotoWithIdOnly = await prisma.accidentPhoto.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AccidentPhotoCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AccidentPhotoCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccidentPhotoPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AccidentPhoto.
   * @param {AccidentPhotoDeleteArgs} args - Arguments to delete one AccidentPhoto.
   * @example
   * // Delete one AccidentPhoto
   * const AccidentPhoto = await prisma.accidentPhoto.delete({
   *   where: {
   *     // ... filter to delete one AccidentPhoto
   *   }
   * })
   * 
   */
  delete<T extends AccidentPhotoDeleteArgs>(args: Prisma.SelectSubset<T, AccidentPhotoDeleteArgs<ExtArgs>>): Prisma.Prisma__AccidentPhotoClient<runtime.Types.Result.GetResult<Prisma.$AccidentPhotoPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AccidentPhoto.
   * @param {AccidentPhotoUpdateArgs} args - Arguments to update one AccidentPhoto.
   * @example
   * // Update one AccidentPhoto
   * const accidentPhoto = await prisma.accidentPhoto.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AccidentPhotoUpdateArgs>(args: Prisma.SelectSubset<T, AccidentPhotoUpdateArgs<ExtArgs>>): Prisma.Prisma__AccidentPhotoClient<runtime.Types.Result.GetResult<Prisma.$AccidentPhotoPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AccidentPhotos.
   * @param {AccidentPhotoDeleteManyArgs} args - Arguments to filter AccidentPhotos to delete.
   * @example
   * // Delete a few AccidentPhotos
   * const { count } = await prisma.accidentPhoto.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AccidentPhotoDeleteManyArgs>(args?: Prisma.SelectSubset<T, AccidentPhotoDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AccidentPhotos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccidentPhotoUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AccidentPhotos
   * const accidentPhoto = await prisma.accidentPhoto.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AccidentPhotoUpdateManyArgs>(args: Prisma.SelectSubset<T, AccidentPhotoUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AccidentPhotos and returns the data updated in the database.
   * @param {AccidentPhotoUpdateManyAndReturnArgs} args - Arguments to update many AccidentPhotos.
   * @example
   * // Update many AccidentPhotos
   * const accidentPhoto = await prisma.accidentPhoto.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AccidentPhotos and only return the `id`
   * const accidentPhotoWithIdOnly = await prisma.accidentPhoto.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AccidentPhotoUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AccidentPhotoUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccidentPhotoPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AccidentPhoto.
   * @param {AccidentPhotoUpsertArgs} args - Arguments to update or create a AccidentPhoto.
   * @example
   * // Update or create a AccidentPhoto
   * const accidentPhoto = await prisma.accidentPhoto.upsert({
   *   create: {
   *     // ... data to create a AccidentPhoto
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AccidentPhoto we want to update
   *   }
   * })
   */
  upsert<T extends AccidentPhotoUpsertArgs>(args: Prisma.SelectSubset<T, AccidentPhotoUpsertArgs<ExtArgs>>): Prisma.Prisma__AccidentPhotoClient<runtime.Types.Result.GetResult<Prisma.$AccidentPhotoPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AccidentPhotos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccidentPhotoCountArgs} args - Arguments to filter AccidentPhotos to count.
   * @example
   * // Count the number of AccidentPhotos
   * const count = await prisma.accidentPhoto.count({
   *   where: {
   *     // ... the filter for the AccidentPhotos we want to count
   *   }
   * })
  **/
  count<T extends AccidentPhotoCountArgs>(
    args?: Prisma.Subset<T, AccidentPhotoCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AccidentPhotoCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AccidentPhoto.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccidentPhotoAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AccidentPhotoAggregateArgs>(args: Prisma.Subset<T, AccidentPhotoAggregateArgs>): Prisma.PrismaPromise<GetAccidentPhotoAggregateType<T>>

  /**
   * Group by AccidentPhoto.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccidentPhotoGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AccidentPhotoGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AccidentPhotoGroupByArgs['orderBy'] }
      : { orderBy?: AccidentPhotoGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AccidentPhotoGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAccidentPhotoGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AccidentPhoto model
 */
readonly fields: AccidentPhotoFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AccidentPhoto.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AccidentPhotoClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  accident<T extends Prisma.AccidentDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AccidentDefaultArgs<ExtArgs>>): Prisma.Prisma__AccidentClient<runtime.Types.Result.GetResult<Prisma.$AccidentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AccidentPhoto model
 */
export interface AccidentPhotoFieldRefs {
  readonly id: Prisma.FieldRef<"AccidentPhoto", 'String'>
  readonly accidentId: Prisma.FieldRef<"AccidentPhoto", 'String'>
  readonly url: Prisma.FieldRef<"AccidentPhoto", 'String'>
  readonly createdAt: Prisma.FieldRef<"AccidentPhoto", 'DateTime'>
}
    

// Custom InputTypes
/**
 * AccidentPhoto findUnique
 */
export type AccidentPhotoFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccidentPhoto
   */
  select?: Prisma.AccidentPhotoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccidentPhoto
   */
  omit?: Prisma.AccidentPhotoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccidentPhotoInclude<ExtArgs> | null
  /**
   * Filter, which AccidentPhoto to fetch.
   */
  where: Prisma.AccidentPhotoWhereUniqueInput
}

/**
 * AccidentPhoto findUniqueOrThrow
 */
export type AccidentPhotoFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccidentPhoto
   */
  select?: Prisma.AccidentPhotoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccidentPhoto
   */
  omit?: Prisma.AccidentPhotoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccidentPhotoInclude<ExtArgs> | null
  /**
   * Filter, which AccidentPhoto to fetch.
   */
  where: Prisma.AccidentPhotoWhereUniqueInput
}

/**
 * AccidentPhoto findFirst
 */
export type AccidentPhotoFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccidentPhoto
   */
  select?: Prisma.AccidentPhotoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccidentPhoto
   */
  omit?: Prisma.AccidentPhotoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccidentPhotoInclude<ExtArgs> | null
  /**
   * Filter, which AccidentPhoto to fetch.
   */
  where?: Prisma.AccidentPhotoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AccidentPhotos to fetch.
   */
  orderBy?: Prisma.AccidentPhotoOrderByWithRelationInput | Prisma.AccidentPhotoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AccidentPhotos.
   */
  cursor?: Prisma.AccidentPhotoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AccidentPhotos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AccidentPhotos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AccidentPhotos.
   */
  distinct?: Prisma.AccidentPhotoScalarFieldEnum | Prisma.AccidentPhotoScalarFieldEnum[]
}

/**
 * AccidentPhoto findFirstOrThrow
 */
export type AccidentPhotoFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccidentPhoto
   */
  select?: Prisma.AccidentPhotoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccidentPhoto
   */
  omit?: Prisma.AccidentPhotoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccidentPhotoInclude<ExtArgs> | null
  /**
   * Filter, which AccidentPhoto to fetch.
   */
  where?: Prisma.AccidentPhotoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AccidentPhotos to fetch.
   */
  orderBy?: Prisma.AccidentPhotoOrderByWithRelationInput | Prisma.AccidentPhotoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AccidentPhotos.
   */
  cursor?: Prisma.AccidentPhotoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AccidentPhotos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AccidentPhotos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AccidentPhotos.
   */
  distinct?: Prisma.AccidentPhotoScalarFieldEnum | Prisma.AccidentPhotoScalarFieldEnum[]
}

/**
 * AccidentPhoto findMany
 */
export type AccidentPhotoFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccidentPhoto
   */
  select?: Prisma.AccidentPhotoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccidentPhoto
   */
  omit?: Prisma.AccidentPhotoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccidentPhotoInclude<ExtArgs> | null
  /**
   * Filter, which AccidentPhotos to fetch.
   */
  where?: Prisma.AccidentPhotoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AccidentPhotos to fetch.
   */
  orderBy?: Prisma.AccidentPhotoOrderByWithRelationInput | Prisma.AccidentPhotoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AccidentPhotos.
   */
  cursor?: Prisma.AccidentPhotoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AccidentPhotos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AccidentPhotos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AccidentPhotos.
   */
  distinct?: Prisma.AccidentPhotoScalarFieldEnum | Prisma.AccidentPhotoScalarFieldEnum[]
}

/**
 * AccidentPhoto create
 */
export type AccidentPhotoCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccidentPhoto
   */
  select?: Prisma.AccidentPhotoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccidentPhoto
   */
  omit?: Prisma.AccidentPhotoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccidentPhotoInclude<ExtArgs> | null
  /**
   * The data needed to create a AccidentPhoto.
   */
  data: Prisma.XOR<Prisma.AccidentPhotoCreateInput, Prisma.AccidentPhotoUncheckedCreateInput>
}

/**
 * AccidentPhoto createMany
 */
export type AccidentPhotoCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AccidentPhotos.
   */
  data: Prisma.AccidentPhotoCreateManyInput | Prisma.AccidentPhotoCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AccidentPhoto createManyAndReturn
 */
export type AccidentPhotoCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccidentPhoto
   */
  select?: Prisma.AccidentPhotoSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AccidentPhoto
   */
  omit?: Prisma.AccidentPhotoOmit<ExtArgs> | null
  /**
   * The data used to create many AccidentPhotos.
   */
  data: Prisma.AccidentPhotoCreateManyInput | Prisma.AccidentPhotoCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccidentPhotoIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AccidentPhoto update
 */
export type AccidentPhotoUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccidentPhoto
   */
  select?: Prisma.AccidentPhotoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccidentPhoto
   */
  omit?: Prisma.AccidentPhotoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccidentPhotoInclude<ExtArgs> | null
  /**
   * The data needed to update a AccidentPhoto.
   */
  data: Prisma.XOR<Prisma.AccidentPhotoUpdateInput, Prisma.AccidentPhotoUncheckedUpdateInput>
  /**
   * Choose, which AccidentPhoto to update.
   */
  where: Prisma.AccidentPhotoWhereUniqueInput
}

/**
 * AccidentPhoto updateMany
 */
export type AccidentPhotoUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AccidentPhotos.
   */
  data: Prisma.XOR<Prisma.AccidentPhotoUpdateManyMutationInput, Prisma.AccidentPhotoUncheckedUpdateManyInput>
  /**
   * Filter which AccidentPhotos to update
   */
  where?: Prisma.AccidentPhotoWhereInput
  /**
   * Limit how many AccidentPhotos to update.
   */
  limit?: number
}

/**
 * AccidentPhoto updateManyAndReturn
 */
export type AccidentPhotoUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccidentPhoto
   */
  select?: Prisma.AccidentPhotoSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AccidentPhoto
   */
  omit?: Prisma.AccidentPhotoOmit<ExtArgs> | null
  /**
   * The data used to update AccidentPhotos.
   */
  data: Prisma.XOR<Prisma.AccidentPhotoUpdateManyMutationInput, Prisma.AccidentPhotoUncheckedUpdateManyInput>
  /**
   * Filter which AccidentPhotos to update
   */
  where?: Prisma.AccidentPhotoWhereInput
  /**
   * Limit how many AccidentPhotos to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccidentPhotoIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AccidentPhoto upsert
 */
export type AccidentPhotoUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccidentPhoto
   */
  select?: Prisma.AccidentPhotoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccidentPhoto
   */
  omit?: Prisma.AccidentPhotoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccidentPhotoInclude<ExtArgs> | null
  /**
   * The filter to search for the AccidentPhoto to update in case it exists.
   */
  where: Prisma.AccidentPhotoWhereUniqueInput
  /**
   * In case the AccidentPhoto found by the `where` argument doesn't exist, create a new AccidentPhoto with this data.
   */
  create: Prisma.XOR<Prisma.AccidentPhotoCreateInput, Prisma.AccidentPhotoUncheckedCreateInput>
  /**
   * In case the AccidentPhoto was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AccidentPhotoUpdateInput, Prisma.AccidentPhotoUncheckedUpdateInput>
}

/**
 * AccidentPhoto delete
 */
export type AccidentPhotoDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccidentPhoto
   */
  select?: Prisma.AccidentPhotoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccidentPhoto
   */
  omit?: Prisma.AccidentPhotoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccidentPhotoInclude<ExtArgs> | null
  /**
   * Filter which AccidentPhoto to delete.
   */
  where: Prisma.AccidentPhotoWhereUniqueInput
}

/**
 * AccidentPhoto deleteMany
 */
export type AccidentPhotoDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AccidentPhotos to delete
   */
  where?: Prisma.AccidentPhotoWhereInput
  /**
   * Limit how many AccidentPhotos to delete.
   */
  limit?: number
}

/**
 * AccidentPhoto without action
 */
export type AccidentPhotoDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccidentPhoto
   */
  select?: Prisma.AccidentPhotoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccidentPhoto
   */
  omit?: Prisma.AccidentPhotoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccidentPhotoInclude<ExtArgs> | null
}
