services:
  app:
    build:
      context: ./web       # <-- Sobe um nível para achar a pasta web (fora de apps)
      dockerfile: Dockerfile
      args:
        VITE_GOOGLE_CLIENT_ID: ${VITE_GOOGLE_CLIENT_ID}
        VITE_API_URL: ${VITE_API_URL}
    container_name: accident_frontend
    restart: always
    env_file:              # <--- ADICIONA ISTO
      - .env
    ports:
      - "3001:3001"
    depends_on:
      - api
      - postgres
      - redis

  api:
    build:
      context: ./api        # <-- Se a API está dentro de apps/api, o caminho relativo ao compose é apenas ./api
      dockerfile: Dockerfile
    container_name: accident_backend
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: accident_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-user_admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password_secure}
      POSTGRES_DB: ${DB_NAME:-accident_report_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: accident_cache
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data: