version: '3.8'

services:
  nginx-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: accident_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
    networks:
      - app-network

  app:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        VITE_GOOGLE_CLIENT_ID: ${VITE_GOOGLE_CLIENT_ID}
        VITE_API_URL: ${VITE_API_URL}
    container_name: accident_frontend
    restart: always
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: accident_backend
    restart: always
    env_file:
      - .env
    networks:
      - app-network
    environment:
      # FIX: Garante que usamos o nome do serviço 'postgres' e não localhost
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?schema=public"
      NODE_ENV: production
      PORT: 3000
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: accident_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: